/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package purchaseordermanagementsystem;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shu Qin
 */
public class EditSale_GUI extends javax.swing.JFrame {
    private DefaultTableModel editsaletable = new DefaultTableModel();
    private String[] editsalecol = {"Sale ID", "Sale Date", "Sale Item Code", "Sale Name", "Sale Item Category", "Sale Quantity", "Sale Unit Price", "Sale Total Price"};
   
    SaleManager saleManager;
    private int row;
    String [] uneditsale;
    
    
    /**
     * Creates new form EditSale_GUI
     */
    public EditSale_GUI(SaleManager saleManager) {
        editsaletable.setColumnIdentifiers(editsalecol); 
        this.saleManager = saleManager;
        initComponents();
        displayTable();
        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Text_eSaleID = new javax.swing.JTextField();
        Text_eSaleItemCode = new javax.swing.JTextField();
        Text_eSaleName = new javax.swing.JTextField();
        Text_eSaleCategory = new javax.swing.JTextField();
        Text_eSaleQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Text_eSaleUnitPrice = new javax.swing.JTextField();
        Text_eTotalPrice = new javax.swing.JLabel();
        Text_eSaleTotal = new javax.swing.JTextField();
        Text_eSaleDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edit_SaleTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Edit Sale");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel2.setText("Sale Date:");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setText("Sale Item Code:");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel4.setText("Sale Item Name:");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel5.setText("Sale Item Category:");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel6.setText("Sale Item Quantity:");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel8.setText("Sale Item Unit Price: ");

        Text_eTotalPrice.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        Text_eTotalPrice.setText("Sale Item Total Price:");

        Text_eSaleDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_eSaleDateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel9.setText("Sale ID:");

        Edit_SaleTable.setModel(editsaletable);
        Edit_SaleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Edit_SaleTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Edit_SaleTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(Text_eTotalPrice))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text_eSaleUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_eSaleTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text_eSaleQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Text_eSaleID)
                                        .addComponent(Text_eSaleItemCode)
                                        .addComponent(Text_eSaleName)
                                        .addComponent(Text_eSaleCategory)
                                        .addComponent(Text_eSaleDate, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))))
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jButton1)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_eSaleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_eSaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Text_eSaleItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_eSaleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Text_eSaleCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_eSaleQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Text_eSaleUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text_eTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Text_eSaleTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                .addComponent(jButton1)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String esaleID = Text_eSaleID.getText();
        String esaleDate = Text_eSaleDate.getText();
        String esaleItemCode = Text_eSaleItemCode.getText();
        String esaleItemName = Text_eSaleName.getText();
        String esaleItemCategory = Text_eSaleCategory.getText();
        String esaleItemQuantity = Text_eSaleQuantity.getText();
        String esaleUnitPrice = Text_eSaleUnitPrice.getText();
       
        //String esaleTotalPrice= Text_eSaleTotal.getText();
        
        
        double editquantity = Double.parseDouble(Text_eSaleQuantity.getText());
        double editunitprice = Double.parseDouble(Text_eSaleUnitPrice.getText());
        double total = editquantity * editunitprice;
        String edittotalprice = String.valueOf(total);
        String esaletotalPrice = edittotalprice;
        String esaleTotalPrice= edittotalprice;
        Text_eSaleTotal.setText(esaleTotalPrice);
        
        String beforequantity = uneditsale[5];
         
        int before = Integer.parseInt(beforequantity);
        int after = Integer.parseInt(Text_eSaleQuantity.getText());
       
        
        
            
        
        
    
       
        String [] editsale = {esaleID, esaleDate, esaleItemCode, esaleItemName, esaleItemCategory,esaleItemQuantity, esaleUnitPrice, esaletotalPrice};
        
       
                
       
        if (before>after){
            int edited = before - after;
            String editvalue = Integer.toString(edited);
            String [] editsaledata1 = {esaleID, esaleDate, esaleItemCode, esaleItemName, esaleItemCategory,editvalue, esaleUnitPrice, esaletotalPrice};
            saleManager.addstock(editsaledata1);
        }
        else {
            int edited = after - before;
            String editvalue = Integer.toString(edited);
            String [] editsaledata1 = {esaleID, esaleDate, esaleItemCode, esaleItemName, esaleItemCategory, editvalue, esaleUnitPrice, esaletotalPrice};
            saleManager.removestock(editsaledata1);
        
        
   }
        
        saleManager.editSale("edit",uneditsale,editsale);
        
        removeTableRow();
        displayTable();
        
        
        
                
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Text_eSaleDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_eSaleDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_eSaleDateActionPerformed

    private void Edit_SaleTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit_SaleTableMouseReleased
        // TODO add your handling code here:
        row = Edit_SaleTable.getSelectedRow();
        
        String esaleid = String.valueOf(editsaletable.getValueAt(row,0));
        String esaledate = String.valueOf(editsaletable.getValueAt(row,1));
        String esaleitemcode = String.valueOf(editsaletable.getValueAt(row,2));
        String esaleitemname = String.valueOf(editsaletable.getValueAt(row,3));
        String esalecategory = String.valueOf(editsaletable.getValueAt(row,4));
        String esalequantity = String.valueOf(editsaletable.getValueAt(row,5));
        String esaleunitprice = String.valueOf(editsaletable.getValueAt(row,6));
        String esaletotal = String.valueOf(editsaletable.getValueAt(row,7));
        
        uneditsale = new String [] {esaleid, esaledate, esaleitemcode, esaleitemname,esalecategory,esalequantity,esaleunitprice,esaletotal};
        
        Text_eSaleID.setText(esaleid);
        Text_eSaleID.setEditable(false);
        Text_eSaleDate.setText(esaledate);
        Text_eSaleDate.setEditable(false);
        Text_eSaleItemCode.setText(esaleitemcode);
        Text_eSaleItemCode.setEditable(false);
        Text_eSaleName.setText(esaleitemname);
        Text_eSaleName.setEditable(false);
        Text_eSaleCategory.setText(esalecategory);
        Text_eSaleCategory.setEditable(false);
        Text_eSaleQuantity.setText(esalequantity);
        Text_eSaleUnitPrice.setText(esaleunitprice);
        Text_eSaleUnitPrice.setEditable(false);
        Text_eSaleTotal.setText(esaletotal);
        Text_eSaleTotal.setEditable(false);
        
        
    }//GEN-LAST:event_Edit_SaleTableMouseReleased
    public void displayTable(){
        
        FileManager getrow = new FileManager("Sale.txt");
        ArrayList<String> rows =  getrow.readFile();
        for(int i=0 ; i< rows.size();i++){
            String line = rows.get(i).toString();
            String[] editsaledata1 = line.split("\\|");
            editsaletable.addRow(editsaledata1);
        }
    }
    public void removeTableRow(){
        int count = editsaletable.getRowCount();
        for (int i = count - 1; i >= 0; i--) {
            editsaletable.removeRow(i);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSale_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSale_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSale_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSale_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SaleManager saleManager = new SaleManager("U00002", "SM01", "SM1234", "SM01@gmail.com", "0134567890", "SaleManager", "S00001");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSale_GUI(saleManager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Edit_SaleTable;
    private javax.swing.JTextField Text_eSaleCategory;
    private javax.swing.JTextField Text_eSaleDate;
    private javax.swing.JTextField Text_eSaleID;
    private javax.swing.JTextField Text_eSaleItemCode;
    private javax.swing.JTextField Text_eSaleName;
    private javax.swing.JTextField Text_eSaleQuantity;
    private javax.swing.JTextField Text_eSaleTotal;
    private javax.swing.JTextField Text_eSaleUnitPrice;
    private javax.swing.JLabel Text_eTotalPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
